name: otrs_lyceum_bot
services:
  bot:
    build: .  # Использует Dockerfile из предыдущего ответа
    container_name: otrs_lyceum_bot
    restart: unless-stopped
    environment:
      DB_HOST: db
      NODE_ENV: production
      TZ: Europe/Moscow
    #volumes:
    #  - ${BOT_DATA_LOCATION:-./bot_data}:/app/data  # Если нужны логи/файлы
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  # Ждёт готовности БД
    #healthcheck:
    #  test: [ "CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1) })" ]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s
    ports:
      - '${APP_PORT:-3000}:${APP_PORT:-3000}'
    networks:
      - otrs_lyceum_bot_network

  db:
    image: postgres:16
    container_name: otrs_lyceum_bot_db
    restart: unless-stopped
    environment:
      PGPORT: ${DB_PORT:-5432}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-otrs_lyceum_bot}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
      TZ: Europe/Moscow
    volumes:
      - ${DB_DATA_LOCATION:-./postgres_data}:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-otrs_lyceum_bot}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - ${DB_PORT:-5432}
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    networks:
      - otrs_lyceum_bot_network

networks:
  otrs_lyceum_bot_network:
    driver: bridge